### PR TITLE
Scale containers to 0 in dashboard

### PR DESCRIPTION
**Pull request by gib**
Closes https://github.com/aptible/dashboard.aptible.com/issues/390 with a pretty small change. We should probably follow up with some messaging updates.

Went through creating a new service, which defaults to 1 container (https://github.com/aptible/api.aptible.com/blob/master/app/models/service.rb#L13) and verified the everything saves as expected through the API.

scale-to-zero

### CODE REVIEW

**Comment by sandersonet** [comment]
:+1:

**Comment by sandersonet** [comment]
@fancyremarker -- I think we can ship this once merged?

**Comment by rwjblue** [comment]
:+1:

**Comment by fancyremarker** [comment]
Yup, good to go. Thanks @gib!

**Pull request merged**
