### PR TITLE
Update sentry version and use custom fork of ember-cli-sentry.

### PR DESCRIPTION
**Pull request by rwjblue**
* Updates Raven to use 1.1.19 (see [changelog](https://github.com/getsentry/raven-js/blob/master/docs/changelog/index.rst) for list of bugfixes), and uses master of ember-cli-sentry to take advantage of upstream Ember plugin fixes.
* Adds a monkey patch to `Raven.captureMessage` to add a `stacktrace` so that we can track down the source of the `[object Object]` errors.

Addresses https://github.com/aptible/dashboard.aptible.com/issues/346.

### CODE REVIEW

**Comment by sandersonet** [comment]
:+1: !

**Comment by rwjblue** [comment]
Just updated to add a monkey patch to `Raven.captureMessage` to add a stacktrace so that we can track down the source of the `[object Object]` errors.

@sandersonet - I'd like to land this, and get it deployed (to at least staging) and see if we can trigger the errors in question.  Any objection?

**Comment by sandersonet** [comment]
Merge at will and it should hit staging shortly thereafter.  Also looks like a minor test failure.

**Comment by rwjblue** [comment]
Whoops, fixed JSHint error and pushed an update.  Will merge once green...

**Pull request merged**
