### PR TITLE
Initial CloudFormation template to document S3/CloudFront setup

### PR DESCRIPTION
**Pull request by fancyremarker**
cc: @rwjblue ... From our pairing session.

TODO: 

* [x] Test that this actually works
* [ ] Notes in README on how to use CFN template
* [ ] Genericize for any static websites
* [ ] Genericize for non-Aptible websites
* [ ] Integrate w/ ember-cli?
* [ ] Custom environment (in config/deploy.js) for ENV-driven sandbox domains (added in https://github.com/fancyremarker/dashboard.aptible.com/pull/1)
* [ ] Blog post(s)!

Question from pairing: Is HTTPS possible for S3 websites?

### CODE REVIEW

**Comment by rwjblue** [comment]
> Question from pairing: Is HTTPS possible for S3 websites?

No, I was wrong.  We can use SSL for S3 resources (as long as they do not have a period in the bucket name), but not for "S3 Websites".  There is a [nice chart](http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html#WebsiteRestEndpointDiff) in the AWS docs explaining the main differences between the website and rest endpoints.

**Comment by fancyremarker** [comment]
That chart is very helpful! I had not seen it before. Thanks.

**Comment by rwjblue** [comment]
Submitted https://github.com/fancyremarker/dashboard.aptible.com/pull/1 against this PR's branch with a number of updates:

* Build `HostedZoneName` as needed (avoid storing in the mapping).
* Remove hardcoded region from template.
* Provide fully qualified domain name for Route53.
* Refactor config/deploy.js.
  * Make a little more DRY
  * Provide helpful error messages when missing required ENV variables.
  * Allow customizing `AWS_BUCKET` (allows deployment to newly built
    CloudFormation stacks).
* Add S3 Website CloudFormation template (no CloudFront).

**Comment by fancyremarker** [comment]
@rwjblue: Merge at will pending passing tests, and let's open issues for the remaining TODO items as appropriate.

**Comment by rwjblue** [comment]
I just confirmed the `cloudfront-s3-website.json` works properly (created https://dashboard-rwjblue.aptible-staging.com/ with it).

**Pull request merged**
