### PR TITLE
Support HTTPS log drains

### PR DESCRIPTION
**Pull request by krallin**
Requires https://github.com/aptible/api.aptible.com/pull/299 in the backend and https://github.com/aptible/sweetness/pull/497 in Sweetness.

This would be used to deploy Logstash as an app-level Logstash log drain using https://github.com/aptible/docker-logstash/pull/1.

@gib, what do you think? Any recommendations / suggestions?

cc @fancyremarker

### CODE REVIEW

**Comment by gib** [comment]
Awesome! I like this a lot. Sorry about the rabbit hole earlier.
You could add a test case to https://github.com/aptible/dashboard.aptible.com/blob/master/tests/acceptance/log-drains/basic-test.js

**Comment by krallin** [comment]
Thanks @gib! 

I added a test that check that submission works and that the port defaults to 443.

**Comment by gib** [comment]
Fantastic! I'm ready to merge...I guess once API and Sweetness are ready.


Thank you @krallin -- thanks for adding the test too!

**Comment by sandersonet** [comment]
This is perfect.  Merge at will.

**Comment by fancyremarker** [comment]
@krallin: Looks like this one [failed its unit test](https://travis-ci.org/aptible/dashboard.aptible.com/builds/107480246#L472) on merge to master, even though it passed on this PR.

**Comment by krallin** [comment]
Did something change between the time I made the PR and we merged it in that could have caused this? (@gib @sandersonet?) If nothing comes to mind, I'll dig for it.

**Comment by sandersonet** [comment]
Not sure why this passed before, but I fixed the broken test here: https://github.com/aptible/dashboard.aptible.com/pull/522

**Comment by krallin** [comment]
Thanks @sandersonet !

**Pull request merged**
