### PR TITLE
One select to rule them all,

### PR DESCRIPTION
**Pull request by blakepettersson**
One select to find them, one select to bring them all and in the
darkness bind them.

This commit consolidates all the various kinds of selects that we
have previously had into one single component - `ultimate-select`.

(The name can be debated and of course changed, but in lieu of a
better one..)

The ultimate-select basically works the same way as the former
primitive-select did. To work with object collections, you choose
the key and value by specifiying `itemKey` and `itemValue` respectively.
This works with both POJOs' and Ember objects.

AFAICS this also removes all usages of Ember views, and now we're
just using components \o/

cc @sandersonet @gib

### CODE REVIEW

**Comment by fancyremarker** [comment]
:clap:

**Comment by sandersonet** [comment]
@blakepettersson  :+1: Perfect!  I'm so glad you tackled this, it's been bugging me for a while.

Later, we should port the new component to `aptible-shared` so that sheriff can get in on this goodness.

**Comment by sandersonet** [comment]
I assume tests pass locally?  Travis didn't run for this PR, maybe force push a new commit to re-trigger Travis?

**Comment by blakepettersson** [comment]
They do pass, I'll try to force push a new commit.

**Comment by sandersonet** [comment]
Travis has been skipping PRs for this repo a lot lately.  Found this issue that seems to suggest it's an issue with GitHub and not Travis: https://github.com/travis-ci/travis-ci/issues/2906

**Comment by gib** [comment]
I'm not sure how I missed this, but it's fantastic! Especially the PR title and commit message :grin:

**Pull request merged**
