### PR TITLE
Add slider for service container size

### PR DESCRIPTION
**Pull request by blakepettersson**
Initial commit for setting the service container size for an app.

* Needs some extra styling
* Needs some extra test cases
* This has not been wired up to set the container size on the api yet
* `Object.assign` is not included in PhantomJS 1.9.x, so the tests
there currently fail. Not sure how to handle that.

Relates to #516.

cc @sandersonet @gib

### CODE REVIEW

**Comment by blakepettersson** [comment]
Pending the merges of aptible/api.aptible.com#316 and aptible/ember-cli-aptible-shared#91, it now sets the `containerSize` on the `Operation` model. We need to reload the `Service` model if `operation.save()` is successful though, would `service.reload()` be enough?

**Comment by sandersonet** [comment]
@blakepettersson -- I think you can replace the `Object.assign` calls with `Ember.$.extend()` to the same affect.

Yep `service.reload()` after the operation saves should be sufficient.  

Would you want to take a stab at also updating the billing overview screen in a follow-up PR? 

Looks great, thanks for this!

**Comment by blakepettersson** [comment]
I found `Ember.merge` which does the same thing as `Object.assign`. 

I'll take a look at the billing overview after merging this PR!

**Comment by blakepettersson** [comment]
I added the ability to disable the slider if the service is on a Sweetness v1 stack.

**Comment by blakepettersson** [comment]
I added some styling for when `.noUi-connect` is disabled. The sliders themselves look a bit wonky, but that is easily solved by wrapping each `container-count` and `slider-wrapper` in a div that's styled with 

```clear: left; 
   height: 50px;
```

I'd have added that myself but I'm not sure what the conventions are for class names etc.

**Comment by sandersonet** [comment]
> I'd have added that myself but I'm not sure what the conventions are for class names etc.

Our general methodology has been:  Styles should either be specific enough that they can belong in a component's css file `app/styles/components/*` or general enough that they can be added to `aptible-shared` in `app/styles/*`.   Since this specifically affects sliders, I'd just add a new class here: https://github.com/aptible/dashboard.aptible.com/blob/master/app/styles/components/slider.scss with those styles.

**Comment by blakepettersson** [comment]
Alright, there should be no more outstanding UI issues. 

Good to :shipit: @sandersonet @gib? 

PS: what do you guys use to create GIF screen captures?

**Comment by chasballew** [comment]
I use http://recordit.co/, @mixonic uses http://www.cockos.com/licecap/

**Comment by sandersonet** [comment]
:+1:  Looks great, thanks @blakepettersson

**Comment by mixonic** [comment]
Monosnap also records videos now :-) but the gif export is poor quality

**Comment by gib** [comment]
I'm a LiceCap fan too!

**Comment by blakepettersson** [comment]
I settled on using Licecap for the future 😄

**Comment by blakepettersson** [comment]
I added a label to make it more obvious that the lower slider scales memory, as well as changing "Saving" to "Scaling" per the suggestion of @krallin. So the final result can be seen below.



scaler-take-2

**Comment by krallin** [comment]
❤️

**Comment by sandersonet** [comment]
:+1:  I'm also wondering if we should disable the sliders and the button while `Scaling...`?

**Comment by gib** [comment]
👏

**Comment by blakepettersson** [comment]
Boom

scaler-take-3

**Pull request merged**
