### PR TITLE
Billing overview screen

### PR DESCRIPTION
**Pull request by sandersonet**
This PR adds a new [billing overview](https://drive.google.com/file/d/0Bxuaj2I3HLq-UlRkdVpuNzJzYW8/view?usp=sharing) screen to the organization settings section of Dashboard.

screenshot 2015-08-25 16 47 11

Thanks for the pairing sessions @gib and @fancyremarker 

For your review @rwjblue

### CODE REVIEW

**Comment by fancyremarker** [comment]
This looks great! Thanks @gib and @sandersonet !

**Comment by gib** [comment]
:+1: This has some definite improvements over my implementation :grin: 
I'll consider a follow up with my currency formatter and the base package info section.

**Comment by rwjblue** [comment]
Lovin' these component integration tests!

**Comment by rwjblue** [comment]
:+1:

**Pull request merged**
