### PR TITLE
Add container size in billing overview

### PR DESCRIPTION
**Pull request by blakepettersson**
This is still a bit rough around the edges, and the tests needs to be updated but I would like some feedback on the ongoing work to add custom container sizes in the billing overview. The current result can be seen below, and this itemises all entries with the price so that it's more clear for a customer.

cc @gib @fancyremarker @sandersonet 

screen shot 2016-05-03 at 17 57 37

### CODE REVIEW

**Comment by wcpines** [comment]
@blakepettersson any chance we could provide environment information as well? 

(Similar to and may obviate the need for https://github.com/aptible/dangerzone/issues/65)

**Comment by blakepettersson** [comment]
@wcpines it's not very visible, but there is already environment information on the billing overview. The `sdfsdf` (good name, I know) on the picture is actually the environment name. All of the resource views iterate over each environment and prints its name along with all its resources under it.

**Comment by sandersonet** [comment]
👏 Excellent

**Comment by blakepettersson** [comment]
@sandersonet the tests are failing with an obscure error on travis, but they pass locally. Do you have any idea what that could be?

**Comment by gib** [comment]
This is awesome!

**Pull request merged**
