### PR TITLE
Frame Buster

### LINKED ISSUE #542: Bust iframes

### PR DESCRIPTION
**Pull request by gib**
Closes #542

Been working on a larger task, but saw a quick path here and decided to knock it out. `bustFrames` blocks pages from sourcing dashboard in a frame/iframe tag. I smoke tested this locally, but couldn’t think of a reasonable way to include a test in the repo without some shenanigans.

Bust some frames Tony!

### CODE REVIEW

**Comment by sandersonet** [comment]
:+1:

**Comment by krallin** [comment]
Should we / can we perhaps set the [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) header on dashboard? 

If we're serving from S3 / CF using static hosting (I believe we are, right?), I seem to remember it's possible to set headers on the bucket objects.

**Comment by sandersonet** [comment]
@krallin is exactly right.  We should be able to just set `X-Frame-Options` on `index.html` by updating our deploy script here: https://github.com/aptible/dashboard.aptible.com/blob/master/lib/ember-deploy-s3-static-index/adapter.js#L42

**Comment by gib** [comment]
Bummer. Looks like this is not supported: https://forums.aws.amazon.com/thread.jspa?threadID=149569
I'll keep looking.

**Comment by gib** [comment]
Closing here... added to `ember-cli-aptible-shared` https://github.com/aptible/ember-cli-aptible-shared/pull/101

**Pull request closed without merging**
