### PR TITLE
Bump Torii to 0.6.0-beta.4

### PR DESCRIPTION
**Pull request by mixonic**
Implements the app side of https://github.com/aptible/ember-cli-aptible-shared/pull/44. Mostly dropping usage of the custom authenticated mixin in favor of Torii's `authenticatedRoute` solution.

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you bump ember-cli-aptible-shared to 0.0.37 to bring in those changes?

**Comment by mixonic** [comment]
pushed.

**Comment by rwjblue** [comment]
@mixonic - I don't see any updates since your comment, and there are still many failed tests (most seem related to the authenticated route mixin changes).

**Comment by mixonic** [comment]
Hm, `ember-cli-aptible-shared` is definitely bumped. Will need to investigate further.

**Comment by mixonic** [comment]
@rwjblue build is green, now that https://github.com/Vestorly/torii/pull/224 is included in the beta release.

**Pull request merged**
